---
title: "CosMx_SMI_best_practices"
author: "Putri Ramadani"
date: "2026-09-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Export Data from AtoMx SIP 
- On AtoMx SIP, select Study -> Study Data.
- Check all the files you wanted to export, and choose SFTP or S3 (AWS) for data download. Please keep in mind that it takes a few hours until these large files are ready to download.
- Download the exported data using SFTP/S3 information that AtoMx SIP gave you.

Example for downloading the exported data using SFTP:
```{bash}
# --- on terminal, view the export folders: ---
sftp -o User="yourusername" na.export.atomx.nanostring.com
sftp> ls -lh
# Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
# enter pasword

# check the size of the data: 
brew install rclone
read -s -p "YourAtoMxPassword" PW; echo
rclone size :sftp:FolderName --sftp-host=na.export.atomx.nanostring.com --sftp-user="yourusername" --sftp-pass=$(rclone obscure "$PW")
# output:
# Total objects: xxxxk
# Total size: xxxx GiB


# --- on another terminal, download the exported data to local computer:
cd ~/YourComputer
caffeinate -i sftp -o User="yourusername" na.export.atomx.nanostring.com
sftp> get -r FolderName

# caffeinate is a terminal-based command, which stops your Mac going to sleep until the command is stopped. Ref: https://www.theapplegeek.co.uk/blog/caffeinate 
# the data download typically takes a few hours depends on the size.
# if you have to close your terminal, and resume the download later, use the command below.
# the -a makes it skip files that already finished and continue partial ones instead of starting over.
sftp> get -ar FolderName
```

Note: If you aim to transfer data to High-Performance Computing cluster, SFTP can be accessed on login node, but not on compute node. So, if you wanted to transfer the data directly to compute node, ask HPC manager for help and inform them the data size to make sure you have enough room to receive it.


# Cell segmentation on AtoMx SIP
- Cell segmentation on AtoMx SIP is performed before creating a study.
- The process takes around 30-40 minutes to complete, no need to stay on AtoMx while cell segmentation is loading. 
- If you're not satisfied with cell segmentation on AtoMx, alternatively you can perform cell segmentation off AtoMx using [cellpose-SAM](https://github.com/mouseland/cellpose). The process can take a few days with GPU, and may take a week or more without GPU. 



